// <auto-generated />
using System;
using Fenicia.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Fenicia.Infrastructure.Migrations
{
    [DbContext(typeof(FeniciaDbContext))]
    [Migration("20210414164359_FeniciaMigra")]
    partial class FeniciaMigra
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Fenicia.Domain.Entities.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ZipCode")
                        .HasMaxLength(25)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PersonId");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("Fenicia.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("Fenicia.Domain.Entities.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Country");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3e14a0da-01c1-4d44-bd98-2474f2edca00"),
                            Name = "Afganistán"
                        },
                        new
                        {
                            Id = new Guid("e72fca70-89ce-4112-8b05-3fabed59b10b"),
                            Name = "Albania"
                        },
                        new
                        {
                            Id = new Guid("3c27e6f9-19b3-453d-a290-ce4c01186956"),
                            Name = "Alemania"
                        },
                        new
                        {
                            Id = new Guid("94c4550a-74cf-4ddb-a1bb-0653c637590d"),
                            Name = "Andorra"
                        },
                        new
                        {
                            Id = new Guid("99063ea1-b8a7-466a-a4a4-3475db01f2ab"),
                            Name = "Angola"
                        },
                        new
                        {
                            Id = new Guid("f100bf46-312c-40fb-bee0-1653eb8a5cce"),
                            Name = "Antigua y Barbuda"
                        },
                        new
                        {
                            Id = new Guid("525ccc19-dcb2-47bd-859e-4cef10dfdaeb"),
                            Name = "Arabia Saudita"
                        },
                        new
                        {
                            Id = new Guid("6cb7027c-7439-4117-895e-d63db473f015"),
                            Name = "Argelia"
                        },
                        new
                        {
                            Id = new Guid("ed96bc37-0618-47dd-8c2f-51b5ef3aa43a"),
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = new Guid("13003134-7a8b-44b5-8226-ad4b5b84730f"),
                            Name = "Armenia"
                        },
                        new
                        {
                            Id = new Guid("9422a832-c998-4bf1-9bac-770e44416ff1"),
                            Name = "Australia"
                        },
                        new
                        {
                            Id = new Guid("82796056-7341-41cc-9a15-ad131b4b9fc4"),
                            Name = "Austria"
                        },
                        new
                        {
                            Id = new Guid("1f71f1c7-73d2-4316-89c3-1380f0fd86d6"),
                            Name = "Azerbaiyán"
                        },
                        new
                        {
                            Id = new Guid("2579c1dc-f67c-4fc3-b3e6-490055ee13e8"),
                            Name = "Bahamas"
                        },
                        new
                        {
                            Id = new Guid("fce34d30-8e61-4982-8c7e-67280a3b39ba"),
                            Name = "Bahréin"
                        },
                        new
                        {
                            Id = new Guid("a7ac6fe9-b090-4a17-a113-3cbb4acc0036"),
                            Name = "Bangladés"
                        },
                        new
                        {
                            Id = new Guid("377649ca-5eee-4f79-bf9f-758c83c289a2"),
                            Name = "Barbados"
                        },
                        new
                        {
                            Id = new Guid("d4bb9969-cdc6-48b9-aa56-f63dd0449e96"),
                            Name = "Bielorrusia"
                        },
                        new
                        {
                            Id = new Guid("4a819bcf-bc84-4265-8fb5-ccb12f7e8949"),
                            Name = "Bélgica"
                        },
                        new
                        {
                            Id = new Guid("20a45ab1-7d3d-43bf-940a-d80ff8fae31b"),
                            Name = "Belice"
                        },
                        new
                        {
                            Id = new Guid("26daa43b-e137-4b09-81f9-521259d43bad"),
                            Name = "Benín"
                        },
                        new
                        {
                            Id = new Guid("dbc9befb-3be6-46ed-bfbf-c9487eddc997"),
                            Name = "Bután"
                        },
                        new
                        {
                            Id = new Guid("6360add2-dc84-44a0-af77-fd1ebd08bf8e"),
                            Name = "Bolivia"
                        },
                        new
                        {
                            Id = new Guid("38f14925-c921-4c3a-a8b8-50d5922f94df"),
                            Name = "Bosnia-Herzegovina"
                        },
                        new
                        {
                            Id = new Guid("2a6281e2-85c1-400c-b7f7-61e56bd00add"),
                            Name = "Botsuana"
                        },
                        new
                        {
                            Id = new Guid("56a366c0-fddc-4bec-a680-9d30dd8917b7"),
                            Name = "Brasil"
                        },
                        new
                        {
                            Id = new Guid("facb408f-bb41-4f16-9a4c-fc66af007550"),
                            Name = "Brunéi"
                        },
                        new
                        {
                            Id = new Guid("7cea07d4-c45c-4bce-8020-10dafc3c2a58"),
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Id = new Guid("2a4ceacc-6660-4ea6-a74a-0bb45ed9e893"),
                            Name = "Burkina Faso"
                        },
                        new
                        {
                            Id = new Guid("4c450d20-811b-4e00-a6ff-78bcd78e0c90"),
                            Name = "Burundi"
                        },
                        new
                        {
                            Id = new Guid("fbe42ccf-c1be-4931-ba74-a538b72a7e18"),
                            Name = "Cabo Verde"
                        },
                        new
                        {
                            Id = new Guid("92d60af0-9dbd-4d88-a144-7d2eb9645707"),
                            Name = "Camboya"
                        },
                        new
                        {
                            Id = new Guid("fb36ce36-2467-4d3d-9ab7-54fe961725a7"),
                            Name = "Camerún"
                        },
                        new
                        {
                            Id = new Guid("99466a00-70e1-4525-8c1c-d6f41c1ac29c"),
                            Name = "Canadá"
                        },
                        new
                        {
                            Id = new Guid("a2930620-048f-4253-a3cd-310417d10c89"),
                            Name = "Chad"
                        },
                        new
                        {
                            Id = new Guid("3b4a710a-4ad6-441c-a89d-1845ec69ba58"),
                            Name = "República Checa"
                        },
                        new
                        {
                            Id = new Guid("f36c37be-b6b5-4353-a30a-007977588cbd"),
                            Name = "Chequia"
                        },
                        new
                        {
                            Id = new Guid("bc2a2d99-e54f-4d88-ae7b-a53829f4c5a1"),
                            Name = "Chile"
                        },
                        new
                        {
                            Id = new Guid("6ba42ad1-f86f-4521-bfb6-c7bf6e9b1d78"),
                            Name = "China"
                        },
                        new
                        {
                            Id = new Guid("012f88fa-8d11-4e41-bbb3-37d129253bc2"),
                            Name = "Chipre"
                        },
                        new
                        {
                            Id = new Guid("4af6bc7a-19fd-4f96-bd63-d166bca4e2e6"),
                            Name = "Colombia"
                        },
                        new
                        {
                            Id = new Guid("d53b6b02-03f9-4274-8db5-87575e8a3b21"),
                            Name = "Comoras"
                        },
                        new
                        {
                            Id = new Guid("1f1ca746-7d6a-453d-af1c-d164210cb0a5"),
                            Name = "Congo"
                        },
                        new
                        {
                            Id = new Guid("5ad4f570-8a13-485f-a792-271ffbc0d723"),
                            Name = "República Democrática del Congo"
                        },
                        new
                        {
                            Id = new Guid("6c06edc3-dd78-4a3d-93ca-15aae9f5894e"),
                            Name = "Corea del Norte"
                        },
                        new
                        {
                            Id = new Guid("85b87f90-2ee1-4568-91e4-97794c7edad1"),
                            Name = "Corea del Sur"
                        },
                        new
                        {
                            Id = new Guid("12f07b3b-1ac5-4b2c-9097-0dcdb26467bc"),
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Id = new Guid("19a25e54-4df5-41af-864e-9102b07955ac"),
                            Name = "Costa de Marfil"
                        },
                        new
                        {
                            Id = new Guid("2f9ed444-e560-43bf-af85-eea8bd36d5fb"),
                            Name = "Croacia"
                        },
                        new
                        {
                            Id = new Guid("1e2583fd-d0b5-4036-8779-ab5b9337b07f"),
                            Name = "Cuba"
                        },
                        new
                        {
                            Id = new Guid("923c1f0e-903a-42f6-b200-339b56fa8d97"),
                            Name = "Dinamarca"
                        },
                        new
                        {
                            Id = new Guid("ccb58fc9-bdea-4628-9b71-fc8cc9c53dea"),
                            Name = "Yibuti"
                        },
                        new
                        {
                            Id = new Guid("7bf43d26-7729-4992-856b-01cd0cda93b2"),
                            Name = "Dominica"
                        },
                        new
                        {
                            Id = new Guid("c7d63674-d278-446b-9905-63d917b7dd6b"),
                            Name = "Ecuador"
                        },
                        new
                        {
                            Id = new Guid("d98718a2-5414-4c65-a7ac-1863aa0349bd"),
                            Name = "Egipto"
                        },
                        new
                        {
                            Id = new Guid("dd0a6777-456a-4d40-9649-7d158f3a32c7"),
                            Name = "El Salvador"
                        },
                        new
                        {
                            Id = new Guid("80669334-3b88-4d82-b859-e169d58a2166"),
                            Name = "Emiratos Árabes Unidos"
                        },
                        new
                        {
                            Id = new Guid("a548aa82-0259-48e8-a26e-598a3d6d2139"),
                            Name = "Eritrea"
                        },
                        new
                        {
                            Id = new Guid("1588460b-04d3-4f34-b60a-460e3d44a900"),
                            Name = "Eslovaquia"
                        },
                        new
                        {
                            Id = new Guid("47137ec5-514d-4c03-b03f-a0e555fff5d2"),
                            Name = "Eslovenia"
                        },
                        new
                        {
                            Id = new Guid("c55305af-f895-4272-93ba-2625be3ad7da"),
                            Name = "España"
                        },
                        new
                        {
                            Id = new Guid("fe4411fa-12a3-4b65-ade5-8576d5970ff9"),
                            Name = "Estados Unidos"
                        },
                        new
                        {
                            Id = new Guid("4361531a-47a2-4b6e-80f7-d2f2683d9fd4"),
                            Name = "Estonia"
                        },
                        new
                        {
                            Id = new Guid("ab87b140-29f5-455f-8477-a51144848d61"),
                            Name = "Etiopía"
                        },
                        new
                        {
                            Id = new Guid("ede962aa-1ff4-494c-8704-f2dbb33b5868"),
                            Name = "Fiyi"
                        },
                        new
                        {
                            Id = new Guid("1a91b2be-c817-424f-b68b-769289f316ea"),
                            Name = "Filipinas"
                        },
                        new
                        {
                            Id = new Guid("833277ab-c65f-4226-8806-a698ba407451"),
                            Name = "Finlandia"
                        },
                        new
                        {
                            Id = new Guid("caefbb6b-621d-40d1-b800-fd50c3c87d07"),
                            Name = "Francia"
                        },
                        new
                        {
                            Id = new Guid("11d18cb2-25ad-439a-a69a-21853d7a9a69"),
                            Name = "Gabón"
                        },
                        new
                        {
                            Id = new Guid("00044285-e211-46b3-98fc-4256be85520a"),
                            Name = "Gambia"
                        },
                        new
                        {
                            Id = new Guid("bc7a0796-4440-43ab-85de-0087ba9e93d7"),
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = new Guid("9c4e6cc8-6660-44d9-ba39-fe0f970ecfc1"),
                            Name = "Ghana"
                        },
                        new
                        {
                            Id = new Guid("ab406fcd-4b5b-4ef2-b29f-6d48f49181e7"),
                            Name = "Granada"
                        },
                        new
                        {
                            Id = new Guid("3a0800ed-1837-427e-93d9-72228691565c"),
                            Name = "Grecia"
                        },
                        new
                        {
                            Id = new Guid("be91bbb1-ea19-4fb5-93b4-06dcec117b91"),
                            Name = "Guatemala"
                        },
                        new
                        {
                            Id = new Guid("d3faf34f-8052-48ca-a8f6-8c323c3a4268"),
                            Name = "Guinea"
                        },
                        new
                        {
                            Id = new Guid("55cb5ebf-e257-4fde-b8f6-97283305f374"),
                            Name = "Guinea-Bissau"
                        },
                        new
                        {
                            Id = new Guid("8bc9d69b-e6f3-4a08-8a5b-71d9b9e86570"),
                            Name = "Guinea Ecuatorial"
                        },
                        new
                        {
                            Id = new Guid("c7644f66-e6a6-49a3-be2d-cd3f3f386b28"),
                            Name = "Guyana"
                        },
                        new
                        {
                            Id = new Guid("46136e45-d072-4eef-be6d-98f9b6f469de"),
                            Name = "Haití"
                        },
                        new
                        {
                            Id = new Guid("8f6189f0-5bea-4acc-8ae4-c01ffb6d5d42"),
                            Name = "Honduras"
                        },
                        new
                        {
                            Id = new Guid("eab5992f-7f21-4a8e-9ff6-e4e4ab171ee0"),
                            Name = "Hungría"
                        },
                        new
                        {
                            Id = new Guid("61c722f3-8178-4fe8-b736-e043c530bcad"),
                            Name = "India"
                        },
                        new
                        {
                            Id = new Guid("ad6c9aef-3804-4159-a9ab-530eb8b18520"),
                            Name = "Indonesia"
                        },
                        new
                        {
                            Id = new Guid("a1b76916-cfa8-43c9-9708-3e4438ea2f9d"),
                            Name = "Irán"
                        },
                        new
                        {
                            Id = new Guid("ea009511-9b6a-4145-8bd2-da5bf8d23e8b"),
                            Name = "Iraq"
                        },
                        new
                        {
                            Id = new Guid("5a8790af-9d6f-4f65-919d-89a8b31bf3a5"),
                            Name = "Irlanda"
                        },
                        new
                        {
                            Id = new Guid("e7749b1e-8424-40c3-b4c5-cbd6bdeb70aa"),
                            Name = "Islandia"
                        },
                        new
                        {
                            Id = new Guid("90a82f40-6f8d-4ac8-bab5-01c02fb3cd7e"),
                            Name = "Israel"
                        },
                        new
                        {
                            Id = new Guid("380de432-35c2-4223-be2c-16321db3d6c2"),
                            Name = "Italia"
                        },
                        new
                        {
                            Id = new Guid("108441d9-4b31-4ed5-a5ae-d41243befd87"),
                            Name = "Jamaica"
                        },
                        new
                        {
                            Id = new Guid("764fbd43-53f9-4d47-b21a-aaa920063b24"),
                            Name = "Japón"
                        },
                        new
                        {
                            Id = new Guid("efe2b337-9094-4d3a-93b9-60325bbee245"),
                            Name = "Jordania"
                        },
                        new
                        {
                            Id = new Guid("1a6e64a6-5a8f-4b0a-9ace-8d804553f8b5"),
                            Name = "Kazajistán"
                        },
                        new
                        {
                            Id = new Guid("de5af868-eada-4bf4-adfe-d6b2322d2623"),
                            Name = "Kenia"
                        },
                        new
                        {
                            Id = new Guid("52d062af-e05a-4506-b600-f519b9876a5e"),
                            Name = "Kirguistán"
                        },
                        new
                        {
                            Id = new Guid("95a26994-2498-4dfc-b5aa-9830bd63e954"),
                            Name = "Kiribati"
                        },
                        new
                        {
                            Id = new Guid("9d9a824b-c987-4ed4-b35f-5b3b5606a6ff"),
                            Name = "Kuwait"
                        },
                        new
                        {
                            Id = new Guid("28d697ce-ea85-4153-aabe-8902abafb0a0"),
                            Name = "Laos"
                        },
                        new
                        {
                            Id = new Guid("97e2713d-d1ca-47bf-b8fa-a2999a713c2a"),
                            Name = "Lesoto"
                        },
                        new
                        {
                            Id = new Guid("bdacf0a2-6ef7-4392-9d84-1734aa53ed05"),
                            Name = "Letonia"
                        },
                        new
                        {
                            Id = new Guid("cc315e4d-657c-4d4b-bd1c-26e4e8dc56bb"),
                            Name = "Líbano"
                        },
                        new
                        {
                            Id = new Guid("f355d332-97a3-4db6-9759-bf2cd4f499d3"),
                            Name = "Liberia"
                        },
                        new
                        {
                            Id = new Guid("d3f8b22e-958c-41b3-99ed-24e549fba133"),
                            Name = "Libia"
                        },
                        new
                        {
                            Id = new Guid("01ab04ef-6edc-4e42-84fc-006f3a46a159"),
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            Id = new Guid("c6b80355-1e8b-41e2-af4c-eaaa2691ec30"),
                            Name = "Lituania"
                        },
                        new
                        {
                            Id = new Guid("33f436ab-fcdc-4ff4-bd90-c22078c349a4"),
                            Name = "Luxemburgo"
                        },
                        new
                        {
                            Id = new Guid("b601126b-1ddb-4011-8a61-2c430c471281"),
                            Name = "Macedonia"
                        },
                        new
                        {
                            Id = new Guid("fac4eb4b-cae8-4a4a-b4a6-4e4db167d902"),
                            Name = "Madagascar"
                        },
                        new
                        {
                            Id = new Guid("56ad51a4-c1ce-4dac-aad5-1b3ad375bf15"),
                            Name = "Malasia"
                        },
                        new
                        {
                            Id = new Guid("5cfe799f-4869-4f44-8892-9aa8b4790338"),
                            Name = "Malaui"
                        },
                        new
                        {
                            Id = new Guid("0c86c6ba-3711-4ce8-9c25-736206611cd6"),
                            Name = "Maldivas"
                        },
                        new
                        {
                            Id = new Guid("26d3921e-2f0d-4c17-ab26-37fbb4986af3"),
                            Name = "Mali / Malí"
                        },
                        new
                        {
                            Id = new Guid("22eec806-cd7e-4d76-9f6e-ef6802579384"),
                            Name = "Malta"
                        },
                        new
                        {
                            Id = new Guid("f8d8b6fa-7d15-4343-b25f-e98304bab76c"),
                            Name = "Marruecos"
                        },
                        new
                        {
                            Id = new Guid("0207fd06-99d6-4178-baca-83ce9e73a37c"),
                            Name = "Islas Marshall"
                        },
                        new
                        {
                            Id = new Guid("2695fbdb-324e-480d-b113-284d044b6d83"),
                            Name = "Mauricio"
                        },
                        new
                        {
                            Id = new Guid("62b199fa-3467-4b03-a884-c758faeda52d"),
                            Name = "Mauritania"
                        },
                        new
                        {
                            Id = new Guid("50e327d7-8989-4cbf-a2a0-75cbb73bae38"),
                            Name = "México"
                        },
                        new
                        {
                            Id = new Guid("2aabac16-52a4-45a8-ada7-041d73a9512f"),
                            Name = "Micronesia"
                        },
                        new
                        {
                            Id = new Guid("1e4edfb4-2305-41e5-8ba4-abaaac5bba39"),
                            Name = "Moldavia"
                        },
                        new
                        {
                            Id = new Guid("8d9de9dc-a101-4d17-a6e3-0b454ded2e10"),
                            Name = "Mónaco"
                        },
                        new
                        {
                            Id = new Guid("2145090a-0e49-4489-89fb-5392b80e488c"),
                            Name = "Mongolia"
                        },
                        new
                        {
                            Id = new Guid("37afb7f3-d59e-461f-9574-ba79e9427ee8"),
                            Name = "Montenegro"
                        },
                        new
                        {
                            Id = new Guid("ec626bab-ac12-4391-9e24-9703c6351f63"),
                            Name = "Mozambique"
                        },
                        new
                        {
                            Id = new Guid("f5e77233-59d7-4996-b7a8-aeaddc43f591"),
                            Name = "Birmania"
                        },
                        new
                        {
                            Id = new Guid("5f7ba73e-8319-4219-aac1-884c0a7d0b78"),
                            Name = "Namibia"
                        },
                        new
                        {
                            Id = new Guid("968f0fed-7db1-400a-943f-000aa68f0e3e"),
                            Name = "Nauru"
                        },
                        new
                        {
                            Id = new Guid("83703175-fd00-47b0-a656-4b95fd36c92f"),
                            Name = "Nepal"
                        },
                        new
                        {
                            Id = new Guid("81f40cd8-98dc-435c-8a99-a6aa239ffaeb"),
                            Name = "Nicaragua"
                        },
                        new
                        {
                            Id = new Guid("4ec62423-f74d-46ed-aea1-97eabe5332cf"),
                            Name = "Níger"
                        },
                        new
                        {
                            Id = new Guid("042c28c1-a1ad-40a8-a7f8-dab6e1f89ef1"),
                            Name = "Nigeria"
                        },
                        new
                        {
                            Id = new Guid("55824565-96b4-403e-9607-715fae2ea988"),
                            Name = "Noruega"
                        },
                        new
                        {
                            Id = new Guid("06dffe94-d5e1-4ebc-b858-41d253fb1679"),
                            Name = "Nueva Zelanda"
                        },
                        new
                        {
                            Id = new Guid("f907a58d-0190-4978-840e-83599e23a0ef"),
                            Name = "Omán"
                        },
                        new
                        {
                            Id = new Guid("e570d276-f41d-4e45-840e-288bc95a7377"),
                            Name = "Países Bajos"
                        },
                        new
                        {
                            Id = new Guid("11018db2-67aa-4d1a-a528-01f4f84dc00c"),
                            Name = "Pakistán"
                        },
                        new
                        {
                            Id = new Guid("166db2cc-ade7-47e7-9a0c-aa433e9fd391"),
                            Name = "Palaos"
                        },
                        new
                        {
                            Id = new Guid("d0e5b10e-1c9d-4eb9-bed0-48b49bca37b9"),
                            Name = "Panamá"
                        },
                        new
                        {
                            Id = new Guid("51e7c80c-904a-4628-8f20-9bfdd3aa7297"),
                            Name = "Papúa Nueva Guinea"
                        },
                        new
                        {
                            Id = new Guid("b7ae1586-bdd2-4533-b1df-bbc5a1190b64"),
                            Name = "Paraguay"
                        },
                        new
                        {
                            Id = new Guid("a8dc0ed6-3300-4794-b852-461c91f326d8"),
                            Name = "Perú"
                        },
                        new
                        {
                            Id = new Guid("00ec51b3-36ca-45c6-91ad-c51571b66fc2"),
                            Name = "Polonia"
                        },
                        new
                        {
                            Id = new Guid("8228c510-bc34-4724-89c0-f321b2a640a6"),
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = new Guid("baf25e11-b12b-43ac-8728-1c17343bfe47"),
                            Name = "Qatar"
                        },
                        new
                        {
                            Id = new Guid("12fcd3af-7c28-440a-a51a-39fc90fce212"),
                            Name = "Reino Unido"
                        },
                        new
                        {
                            Id = new Guid("85cfcda1-7d8c-414a-9efa-c542ada865b6"),
                            Name = "República Centroafricana"
                        },
                        new
                        {
                            Id = new Guid("aef1fdc0-aef3-4438-bb49-d6c5be4762cc"),
                            Name = "República Dominicana"
                        },
                        new
                        {
                            Id = new Guid("6d8a035a-728e-4a0a-ae29-1ed2b36f1b18"),
                            Name = "Rumanía / Rumania"
                        },
                        new
                        {
                            Id = new Guid("77013511-99bb-409c-acab-d74e52f59dfa"),
                            Name = "Rusia"
                        },
                        new
                        {
                            Id = new Guid("da3c00d2-afad-44be-be5a-245c4bcafc13"),
                            Name = "Ruanda"
                        },
                        new
                        {
                            Id = new Guid("47f457e7-f7ea-4aec-ab33-852b8f0e3bfc"),
                            Name = "San Cristóbal y Nieves"
                        },
                        new
                        {
                            Id = new Guid("88bd42a3-dd59-48ac-a865-77fa1e3f5a3c"),
                            Name = "Islas Salomón"
                        },
                        new
                        {
                            Id = new Guid("2ad9f129-959f-4639-b0bd-ffa7ff15c616"),
                            Name = "Samoa"
                        },
                        new
                        {
                            Id = new Guid("8bce79fb-4899-41b8-b938-12bfab220115"),
                            Name = "San Marino"
                        },
                        new
                        {
                            Id = new Guid("14804a7a-df87-41a4-8f6d-6c6e5639bd4f"),
                            Name = "Santa Lucía"
                        },
                        new
                        {
                            Id = new Guid("c6b28736-a46b-4dc3-a0c1-5c55090e8455"),
                            Name = "Ciudad del Vaticano"
                        },
                        new
                        {
                            Id = new Guid("a27de31d-bbe6-4280-b581-964d00fcf988"),
                            Name = "Santo Tomé y Príncipe"
                        },
                        new
                        {
                            Id = new Guid("1f51327c-04e8-4588-ae06-aea0a4035634"),
                            Name = "San Vicente y las Granadinas"
                        },
                        new
                        {
                            Id = new Guid("375f9569-abd7-4431-b160-8d7b354a31e7"),
                            Name = "Senegal"
                        },
                        new
                        {
                            Id = new Guid("86de924f-e2ab-4fac-a39a-ae653759baed"),
                            Name = "Serbia"
                        },
                        new
                        {
                            Id = new Guid("5e856b53-a0af-4d68-8331-8030cbf0d5d7"),
                            Name = "Seychelles"
                        },
                        new
                        {
                            Id = new Guid("5e1ac8eb-db23-4127-b1e6-4062f44c805b"),
                            Name = "Sierra Leona"
                        },
                        new
                        {
                            Id = new Guid("acb1a1c3-336f-4d9b-a9fd-a3e1b3a13395"),
                            Name = "Singapur"
                        },
                        new
                        {
                            Id = new Guid("b86a6245-a5b8-4601-a6d9-c563467857ab"),
                            Name = "Siria"
                        },
                        new
                        {
                            Id = new Guid("77129136-d214-42dc-9bc4-86fa493063ae"),
                            Name = "Somalia"
                        },
                        new
                        {
                            Id = new Guid("16b83289-06e1-40fe-a6b8-3b9a3cb59622"),
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            Id = new Guid("36a121e9-333a-40ac-a34d-c36d89358a0b"),
                            Name = "Sudáfrica"
                        },
                        new
                        {
                            Id = new Guid("29dadf90-02e6-41e6-9607-44820753fa79"),
                            Name = "Sudán"
                        },
                        new
                        {
                            Id = new Guid("639b4e2e-4e68-4d47-b8fe-d3537877b35d"),
                            Name = "Sudán del Sur"
                        },
                        new
                        {
                            Id = new Guid("e9d2ef7a-f621-4586-abd2-c0d9addb81e6"),
                            Name = "Suecia"
                        },
                        new
                        {
                            Id = new Guid("2f937d95-7059-40ef-86af-43158d382c72"),
                            Name = "Suiza"
                        },
                        new
                        {
                            Id = new Guid("71e2c724-e9bb-4ff1-a306-0b0e3ba35496"),
                            Name = "Surinam"
                        },
                        new
                        {
                            Id = new Guid("c65bc010-3e72-4eaf-a533-77109b4a5664"),
                            Name = "Suazilandia"
                        },
                        new
                        {
                            Id = new Guid("c5c84c5f-cedb-4dfc-a028-83b6852499e5"),
                            Name = "Tailandia"
                        },
                        new
                        {
                            Id = new Guid("52654f13-f1d4-44b9-92ef-ef5b363cc0d9"),
                            Name = "Tanzania"
                        },
                        new
                        {
                            Id = new Guid("4a8c0704-5eca-46e8-ac6d-bc3ef4a633d8"),
                            Name = "Tayikistán"
                        },
                        new
                        {
                            Id = new Guid("261e9d62-5721-4c0c-bc96-e4ac09af726e"),
                            Name = "Timor Oriental"
                        },
                        new
                        {
                            Id = new Guid("2b3a06ce-1055-481e-ae9b-92d3e8faef2e"),
                            Name = "Togo"
                        },
                        new
                        {
                            Id = new Guid("8e9cac2d-acb7-49b5-a73b-328955d11d1b"),
                            Name = "Tonga"
                        },
                        new
                        {
                            Id = new Guid("5fffbd9c-9a1d-4aca-9c4f-10a327a425e0"),
                            Name = "Trinidad y Tobago"
                        },
                        new
                        {
                            Id = new Guid("cf2d12cf-6326-428a-a858-2e65ff4a81d6"),
                            Name = "Túnez"
                        },
                        new
                        {
                            Id = new Guid("dafdbc62-137a-4f0e-912c-718cc74c789b"),
                            Name = "Turkmenistán"
                        },
                        new
                        {
                            Id = new Guid("d017a44f-d307-4f89-a2f5-5f71771ad1a0"),
                            Name = "Turquía"
                        },
                        new
                        {
                            Id = new Guid("0a0f1293-de68-4e48-aaf7-bf56a3a08f96"),
                            Name = "Tuvalu"
                        },
                        new
                        {
                            Id = new Guid("f04149aa-765b-4a8a-90e8-b4d1d2608cd1"),
                            Name = "Ucrania"
                        },
                        new
                        {
                            Id = new Guid("ac2d0298-3989-47b9-b983-cf9914dc88c3"),
                            Name = "Uganda"
                        },
                        new
                        {
                            Id = new Guid("c2c69859-510b-4ed2-9ba3-b51cc8de0f06"),
                            Name = "Uruguay"
                        },
                        new
                        {
                            Id = new Guid("c146a58b-1fc1-4f94-b943-833717f7c799"),
                            Name = "Uzbekistán"
                        },
                        new
                        {
                            Id = new Guid("5a27b3ee-9c9b-4965-b9d3-653c8dfe5f4d"),
                            Name = "Vanuatu"
                        },
                        new
                        {
                            Id = new Guid("b4e793a4-c379-47be-aa31-9d3107fc010f"),
                            Name = "Venezuela"
                        },
                        new
                        {
                            Id = new Guid("24d1fb63-6336-4f29-af05-687ba00ebd16"),
                            Name = "Vietnam"
                        },
                        new
                        {
                            Id = new Guid("22853c26-04d3-4999-a2de-74bd4e7e6d22"),
                            Name = "Yemen"
                        },
                        new
                        {
                            Id = new Guid("2608a230-5135-47bb-8d11-ff786d088b38"),
                            Name = "Zambia"
                        },
                        new
                        {
                            Id = new Guid("9503b8ef-3c01-41ff-8743-33b5514401a7"),
                            Name = "Zimbabue"
                        });
                });

            modelBuilder.Entity("Fenicia.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FiscalName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nif")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.Property<string>("TradeName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("Fenicia.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignamentDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DeliveryAddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Iva")
                        .HasColumnType("decimal(8,2)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("TerminationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DeliveryAddressId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("Fenicia.Domain.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(8,2)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("Fenicia.Domain.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("varchar(9)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Dni")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("Fenicia.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(8,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("Fenicia.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("Fenicia.Domain.Entities.Employee", b =>
                {
                    b.HasBaseType("Fenicia.Domain.Entities.Person");

                    b.Property<string>("Job")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(8,2)");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("Fenicia.Domain.Entities.Address", b =>
                {
                    b.HasOne("Fenicia.Domain.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fenicia.Domain.Entities.Customer", "Customer")
                        .WithMany("Addresses")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Fenicia.Domain.Entities.Person", "Person")
                        .WithMany("Addresses")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Country");

                    b.Navigation("Customer");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Fenicia.Domain.Entities.Order", b =>
                {
                    b.HasOne("Fenicia.Domain.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Fenicia.Domain.Entities.Address", "DeliveryAddress")
                        .WithMany("Orders")
                        .HasForeignKey("DeliveryAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fenicia.Domain.Entities.Employee", "Employee")
                        .WithMany("Orders")
                        .HasForeignKey("EmployeeId");

                    b.Navigation("Customer");

                    b.Navigation("DeliveryAddress");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Fenicia.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("Fenicia.Domain.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fenicia.Domain.Entities.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Fenicia.Domain.Entities.Person", b =>
                {
                    b.HasOne("Fenicia.Domain.Entities.User", "User")
                        .WithOne("Person")
                        .HasForeignKey("Fenicia.Domain.Entities.Person", "UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Fenicia.Domain.Entities.Product", b =>
                {
                    b.HasOne("Fenicia.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Fenicia.Domain.Entities.Employee", b =>
                {
                    b.HasOne("Fenicia.Domain.Entities.Person", null)
                        .WithOne()
                        .HasForeignKey("Fenicia.Domain.Entities.Employee", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fenicia.Domain.Entities.Address", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Fenicia.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Fenicia.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Fenicia.Domain.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Fenicia.Domain.Entities.Person", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("Fenicia.Domain.Entities.Product", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Fenicia.Domain.Entities.User", b =>
                {
                    b.Navigation("Person");
                });

            modelBuilder.Entity("Fenicia.Domain.Entities.Employee", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
