// <auto-generated />
using System;
using Fenicia.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Fenicia.Infrastructure.Migrations
{
    [DbContext(typeof(FeniciaDbContext))]
    partial class FeniciaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Fenicia.Domain.Entities.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ZipCode")
                        .HasMaxLength(25)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PersonId");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("Fenicia.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("Fenicia.Domain.Entities.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Country");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c1342f40-a7b6-47bd-9189-acf619c97545"),
                            Name = "Afganistán"
                        },
                        new
                        {
                            Id = new Guid("9f5cf37f-43ef-47a9-9a43-f27b1379da61"),
                            Name = "Albania"
                        },
                        new
                        {
                            Id = new Guid("02558442-b151-40fd-a174-e24f730914e6"),
                            Name = "Alemania"
                        },
                        new
                        {
                            Id = new Guid("e5684620-4d14-4c31-8183-289aa66dc7dc"),
                            Name = "Andorra"
                        },
                        new
                        {
                            Id = new Guid("f8ccfa42-267f-4912-a2ed-bb8f291028c4"),
                            Name = "Angola"
                        },
                        new
                        {
                            Id = new Guid("952e6417-20bb-45e4-99df-9ff7512c967f"),
                            Name = "Antigua y Barbuda"
                        },
                        new
                        {
                            Id = new Guid("3638665f-ca68-4130-86cf-2bbd8f0f23e9"),
                            Name = "Arabia Saudita"
                        },
                        new
                        {
                            Id = new Guid("6cfd2c99-8b1e-41b5-8dd7-9a7985ddbb0b"),
                            Name = "Argelia"
                        },
                        new
                        {
                            Id = new Guid("1d0d50c1-a2fc-4dc3-965d-a5c2ad798370"),
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = new Guid("d0f3e01d-a32a-40a9-af03-b745d7fe0a83"),
                            Name = "Armenia"
                        },
                        new
                        {
                            Id = new Guid("621cd71b-1494-4d5e-9268-55ed89cc825f"),
                            Name = "Australia"
                        },
                        new
                        {
                            Id = new Guid("a39c82ff-5ba7-4709-a2ee-f7b9569deff1"),
                            Name = "Austria"
                        },
                        new
                        {
                            Id = new Guid("48b981bc-dca3-4fb5-810f-0cbccdc223e9"),
                            Name = "Azerbaiyán"
                        },
                        new
                        {
                            Id = new Guid("e0d338b8-c6e7-4745-9551-8dc2aed0682f"),
                            Name = "Bahamas"
                        },
                        new
                        {
                            Id = new Guid("f5bbe03b-9df3-488f-9eaa-a3a80078efc2"),
                            Name = "Bahréin"
                        },
                        new
                        {
                            Id = new Guid("4e1e7010-0c73-4b90-9517-84d280b34e23"),
                            Name = "Bangladés"
                        },
                        new
                        {
                            Id = new Guid("6cd71326-0bcd-4b81-9545-c51e2ba46d87"),
                            Name = "Barbados"
                        },
                        new
                        {
                            Id = new Guid("5f4c2942-6932-4def-ae1b-98dc5a08b313"),
                            Name = "Bielorrusia"
                        },
                        new
                        {
                            Id = new Guid("67735363-36c5-48bf-bfcf-b5f38ee88fdb"),
                            Name = "Bélgica"
                        },
                        new
                        {
                            Id = new Guid("27709fc9-4eef-4f6a-b155-b8e0bc7a327c"),
                            Name = "Belice"
                        },
                        new
                        {
                            Id = new Guid("d715ce6f-3299-4af1-aeaf-665d960ddfb9"),
                            Name = "Benín"
                        },
                        new
                        {
                            Id = new Guid("79921f91-4ae4-4e52-9b5a-acbd19112f8c"),
                            Name = "Bután"
                        },
                        new
                        {
                            Id = new Guid("8321f44c-1cb9-4551-9b89-71222784e6d7"),
                            Name = "Bolivia"
                        },
                        new
                        {
                            Id = new Guid("7aa4be8c-cdbf-4bab-98fa-ec49553468ae"),
                            Name = "Bosnia-Herzegovina"
                        },
                        new
                        {
                            Id = new Guid("af0a8869-03b0-43cf-8745-d1d062da518d"),
                            Name = "Botsuana"
                        },
                        new
                        {
                            Id = new Guid("a2561f8c-eef2-4ea3-bf49-bd8aa391eec3"),
                            Name = "Brasil"
                        },
                        new
                        {
                            Id = new Guid("8d438d39-64ab-42d7-8704-b54478d45ab0"),
                            Name = "Brunéi"
                        },
                        new
                        {
                            Id = new Guid("c69e1927-2227-4065-8222-508b3d15ee32"),
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Id = new Guid("b354a51e-803c-4fab-b8a0-4089c16b0f8e"),
                            Name = "Burkina Faso"
                        },
                        new
                        {
                            Id = new Guid("f47494ea-4ded-4428-9932-3192e5649daa"),
                            Name = "Burundi"
                        },
                        new
                        {
                            Id = new Guid("30c4b67a-1101-405e-a8da-fe4725521bea"),
                            Name = "Cabo Verde"
                        },
                        new
                        {
                            Id = new Guid("7e739335-1cf8-4d25-a620-a8a5acc9b7b9"),
                            Name = "Camboya"
                        },
                        new
                        {
                            Id = new Guid("aa4e84f2-a9ef-4fc0-b8ee-fb1e4cc99e03"),
                            Name = "Camerún"
                        },
                        new
                        {
                            Id = new Guid("73a6b646-23c1-4814-a989-7b60ac11f28d"),
                            Name = "Canadá"
                        },
                        new
                        {
                            Id = new Guid("f78278a8-5b0f-4337-ae14-f759df3662ac"),
                            Name = "Chad"
                        },
                        new
                        {
                            Id = new Guid("bad8d039-39f8-4026-a9ca-4ed993cbb13a"),
                            Name = "República Checa"
                        },
                        new
                        {
                            Id = new Guid("ee7bf51b-2b26-4d9b-b41e-6afb3bacea55"),
                            Name = "Chequia"
                        },
                        new
                        {
                            Id = new Guid("bc8588d8-a460-4f43-9eba-4bccd2973fc3"),
                            Name = "Chile"
                        },
                        new
                        {
                            Id = new Guid("eb4f5bfe-c34e-4472-b377-66d1d635a91d"),
                            Name = "China"
                        },
                        new
                        {
                            Id = new Guid("6dfd214d-d4e5-4185-aa90-d64bc1051413"),
                            Name = "Chipre"
                        },
                        new
                        {
                            Id = new Guid("0dcf9174-5f69-46cb-ba98-faa3fbb7f955"),
                            Name = "Colombia"
                        },
                        new
                        {
                            Id = new Guid("1b210950-aac9-46d4-b96f-0a322b9d381a"),
                            Name = "Comoras"
                        },
                        new
                        {
                            Id = new Guid("bce4c838-2a3d-4662-b096-830ee2ba2e13"),
                            Name = "Congo"
                        },
                        new
                        {
                            Id = new Guid("b421fb21-e290-4a0b-9ef0-49d6af57eae8"),
                            Name = "República Democrática del Congo"
                        },
                        new
                        {
                            Id = new Guid("1cbaae56-fd91-4997-bacd-aa7597bab888"),
                            Name = "Corea del Norte"
                        },
                        new
                        {
                            Id = new Guid("45b3c6bb-b509-44d6-b1dc-4010f9d6d95d"),
                            Name = "Corea del Sur"
                        },
                        new
                        {
                            Id = new Guid("ff2479b4-56cb-4b3b-9d51-beddaccee8b7"),
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Id = new Guid("42f6a69a-d826-4b33-a4a2-d362ae5612ef"),
                            Name = "Costa de Marfil"
                        },
                        new
                        {
                            Id = new Guid("84476296-6ea4-41b2-8c5e-d31eb0387438"),
                            Name = "Croacia"
                        },
                        new
                        {
                            Id = new Guid("0d4cf6a3-1b57-4928-9cdc-ee04e0e05bc7"),
                            Name = "Cuba"
                        },
                        new
                        {
                            Id = new Guid("057be884-2abf-4fa7-aa77-bac776a87c5b"),
                            Name = "Dinamarca"
                        },
                        new
                        {
                            Id = new Guid("b5cf2399-8b10-4880-8e2e-363deaa62650"),
                            Name = "Yibuti"
                        },
                        new
                        {
                            Id = new Guid("86846016-01b6-4cf4-9451-9571d57f993f"),
                            Name = "Dominica"
                        },
                        new
                        {
                            Id = new Guid("d8a15ddf-66ce-455f-b8cc-28c4d0ac97a6"),
                            Name = "Ecuador"
                        },
                        new
                        {
                            Id = new Guid("6e799d6f-06df-4506-9809-720ac446d2a6"),
                            Name = "Egipto"
                        },
                        new
                        {
                            Id = new Guid("5a16ba1d-19bb-42f8-b351-841d18b3d82c"),
                            Name = "El Salvador"
                        },
                        new
                        {
                            Id = new Guid("a232884d-2100-43a5-ba9f-a9cacb8b9a98"),
                            Name = "Emiratos Árabes Unidos"
                        },
                        new
                        {
                            Id = new Guid("47acdd84-0418-4a44-b3f3-840f790a3d92"),
                            Name = "Eritrea"
                        },
                        new
                        {
                            Id = new Guid("0b2a6222-6099-4d27-88e8-e8d2be96da02"),
                            Name = "Eslovaquia"
                        },
                        new
                        {
                            Id = new Guid("c9d8f3eb-ab60-401d-bd12-9523bad7bdba"),
                            Name = "Eslovenia"
                        },
                        new
                        {
                            Id = new Guid("ff827a8e-9524-4cbe-a995-e86becb9bfda"),
                            Name = "España"
                        },
                        new
                        {
                            Id = new Guid("35875578-e7ad-48a9-8c52-72bde77e0d6e"),
                            Name = "Estados Unidos"
                        },
                        new
                        {
                            Id = new Guid("2b7d3c75-8aee-4f5e-922d-bac6a859aa21"),
                            Name = "Estonia"
                        },
                        new
                        {
                            Id = new Guid("00c01e08-6538-4574-8c7d-a059b33eb5e4"),
                            Name = "Etiopía"
                        },
                        new
                        {
                            Id = new Guid("8e0831dc-a7ac-4c71-876c-cd8ca04515a2"),
                            Name = "Fiyi"
                        },
                        new
                        {
                            Id = new Guid("965ec973-356b-4c1d-a8b3-4052184d91c0"),
                            Name = "Filipinas"
                        },
                        new
                        {
                            Id = new Guid("8fb32fc3-1a76-459b-9c45-6376a84a47cc"),
                            Name = "Finlandia"
                        },
                        new
                        {
                            Id = new Guid("1d763fc2-d665-43b4-a311-4bbf1b8275a5"),
                            Name = "Francia"
                        },
                        new
                        {
                            Id = new Guid("bf9fa9fd-c3cf-41b1-b30e-78ad2f55f2f9"),
                            Name = "Gabón"
                        },
                        new
                        {
                            Id = new Guid("d43c4c73-0b61-4073-83f2-897352e515ef"),
                            Name = "Gambia"
                        },
                        new
                        {
                            Id = new Guid("1c4fdccb-22eb-493c-bd43-f8293af0cff2"),
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = new Guid("498bff17-41dd-4acc-a6d6-d45005c3bc75"),
                            Name = "Ghana"
                        },
                        new
                        {
                            Id = new Guid("fc5acbc7-ed0b-42de-bc7a-352585305e21"),
                            Name = "Granada"
                        },
                        new
                        {
                            Id = new Guid("b3944b38-e845-49a0-9557-eac03f9cde79"),
                            Name = "Grecia"
                        },
                        new
                        {
                            Id = new Guid("ebe2842b-7c7b-48e7-8e61-befbcf23358a"),
                            Name = "Guatemala"
                        },
                        new
                        {
                            Id = new Guid("2c622981-3aa4-4e0b-8aef-e48dc64762d1"),
                            Name = "Guinea"
                        },
                        new
                        {
                            Id = new Guid("5639c0e9-6f60-40cb-bf2b-9c6ed6723a5d"),
                            Name = "Guinea-Bissau"
                        },
                        new
                        {
                            Id = new Guid("060b1e5e-6eac-48a7-a3e3-16f33adc8fee"),
                            Name = "Guinea Ecuatorial"
                        },
                        new
                        {
                            Id = new Guid("a3cab066-db41-4ad6-a894-e0acff466819"),
                            Name = "Guyana"
                        },
                        new
                        {
                            Id = new Guid("2ec6c08a-53f7-4721-aa48-d5503b9f0718"),
                            Name = "Haití"
                        },
                        new
                        {
                            Id = new Guid("d9368b23-d8da-4b82-8c19-f82ba2e056df"),
                            Name = "Honduras"
                        },
                        new
                        {
                            Id = new Guid("73dc978f-bb27-4304-a21c-7d2f5e5d4759"),
                            Name = "Hungría"
                        },
                        new
                        {
                            Id = new Guid("65ff4ee5-1351-4180-9fc6-84961ec6fd28"),
                            Name = "India"
                        },
                        new
                        {
                            Id = new Guid("d1d702ef-e144-4954-bb84-53e85ce8f775"),
                            Name = "Indonesia"
                        },
                        new
                        {
                            Id = new Guid("6025cfed-8947-4974-9369-96623f8e8ef6"),
                            Name = "Irán"
                        },
                        new
                        {
                            Id = new Guid("3b808026-b9d2-430a-8a29-cdd760029a17"),
                            Name = "Iraq"
                        },
                        new
                        {
                            Id = new Guid("80ece93c-ed98-49df-972f-3c5ae3a1276f"),
                            Name = "Irlanda"
                        },
                        new
                        {
                            Id = new Guid("48d22077-0abf-4242-9559-5533ec64cdca"),
                            Name = "Islandia"
                        },
                        new
                        {
                            Id = new Guid("054c81a3-ce01-4e6e-8428-a46ede791d3e"),
                            Name = "Israel"
                        },
                        new
                        {
                            Id = new Guid("10c69b72-9954-49d5-9153-c4527605bd4a"),
                            Name = "Italia"
                        },
                        new
                        {
                            Id = new Guid("577a758a-6170-40d8-8a11-fe436a72a1df"),
                            Name = "Jamaica"
                        },
                        new
                        {
                            Id = new Guid("edde2470-367b-4e4e-9e19-dbced62c78ea"),
                            Name = "Japón"
                        },
                        new
                        {
                            Id = new Guid("d3e91207-e6ad-4b17-bb2a-ce45788b0c1f"),
                            Name = "Jordania"
                        },
                        new
                        {
                            Id = new Guid("9d39a9ec-3d1c-419b-9b49-b3e6efca9924"),
                            Name = "Kazajistán"
                        },
                        new
                        {
                            Id = new Guid("0999a7e6-fa9f-432f-ada9-a4cfba20c3b0"),
                            Name = "Kenia"
                        },
                        new
                        {
                            Id = new Guid("45b5f5dd-725e-4b92-bf73-d253ebd714da"),
                            Name = "Kirguistán"
                        },
                        new
                        {
                            Id = new Guid("cc568911-a762-4e97-80f5-9d29e735c0a0"),
                            Name = "Kiribati"
                        },
                        new
                        {
                            Id = new Guid("8182b70e-6b05-4c32-b0b5-122edb5db04f"),
                            Name = "Kuwait"
                        },
                        new
                        {
                            Id = new Guid("57701f80-c39d-4e04-aa05-ab3d0fe27dad"),
                            Name = "Laos"
                        },
                        new
                        {
                            Id = new Guid("5d2a3fe1-ced5-450b-8ea2-693228543445"),
                            Name = "Lesoto"
                        },
                        new
                        {
                            Id = new Guid("8786d78f-0075-4fc3-88af-109e442d618f"),
                            Name = "Letonia"
                        },
                        new
                        {
                            Id = new Guid("512bfabd-a709-4d56-8c93-26e745d6e226"),
                            Name = "Líbano"
                        },
                        new
                        {
                            Id = new Guid("97f28e74-59e5-455b-bd74-ab659ff5a357"),
                            Name = "Liberia"
                        },
                        new
                        {
                            Id = new Guid("4ceddccc-2d21-4d1e-a0f4-07d0609fbc66"),
                            Name = "Libia"
                        },
                        new
                        {
                            Id = new Guid("2f3a452f-2563-47bc-b8eb-038d4dfef44b"),
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            Id = new Guid("e76f41ab-dd3f-4fa7-8ad9-1239c47d1d0b"),
                            Name = "Lituania"
                        },
                        new
                        {
                            Id = new Guid("d4ace6c4-8f77-4c07-bec2-0fa85d735bb9"),
                            Name = "Luxemburgo"
                        },
                        new
                        {
                            Id = new Guid("a542e7be-1dbc-4e94-b865-be73d958d21b"),
                            Name = "Macedonia"
                        },
                        new
                        {
                            Id = new Guid("a6b48617-32ff-4ee4-9351-ad0bb1cd1279"),
                            Name = "Madagascar"
                        },
                        new
                        {
                            Id = new Guid("8edd6643-9980-42fa-9c71-ccb0796ea630"),
                            Name = "Malasia"
                        },
                        new
                        {
                            Id = new Guid("b64d3565-ed46-490b-8675-4e757bf37c69"),
                            Name = "Malaui"
                        },
                        new
                        {
                            Id = new Guid("c11b1034-8991-4aac-ad5e-280c1867703e"),
                            Name = "Maldivas"
                        },
                        new
                        {
                            Id = new Guid("b75500e9-6425-474c-a384-9d8591a80cb3"),
                            Name = "Mali / Malí"
                        },
                        new
                        {
                            Id = new Guid("0fc15cdb-b3b1-4c18-9089-b4f5063ed761"),
                            Name = "Malta"
                        },
                        new
                        {
                            Id = new Guid("814c92dc-022b-413a-9e30-529cea551e48"),
                            Name = "Marruecos"
                        },
                        new
                        {
                            Id = new Guid("172f2f25-756e-4b83-a159-c3755a024c20"),
                            Name = "Islas Marshall"
                        },
                        new
                        {
                            Id = new Guid("14912512-9c3f-4499-9962-f30d83f0ea60"),
                            Name = "Mauricio"
                        },
                        new
                        {
                            Id = new Guid("087234e2-d5d8-4681-88d5-c6bfe07162b7"),
                            Name = "Mauritania"
                        },
                        new
                        {
                            Id = new Guid("c656a508-6aa0-4615-b656-3b776fdae1ae"),
                            Name = "México"
                        },
                        new
                        {
                            Id = new Guid("210db976-d1c4-40c3-8b5c-95a9a100d54d"),
                            Name = "Micronesia"
                        },
                        new
                        {
                            Id = new Guid("da75b499-db20-4dcb-9395-df9ea2baca33"),
                            Name = "Moldavia"
                        },
                        new
                        {
                            Id = new Guid("625a81e6-8c8e-4115-8dd3-8f9040abba8c"),
                            Name = "Mónaco"
                        },
                        new
                        {
                            Id = new Guid("3c443718-f4e6-4668-a22c-063d20a4815b"),
                            Name = "Mongolia"
                        },
                        new
                        {
                            Id = new Guid("f18dec61-fd74-4356-9461-4c58548997e4"),
                            Name = "Montenegro"
                        },
                        new
                        {
                            Id = new Guid("efa30cd2-e1eb-4464-bcb3-780367b3b3a9"),
                            Name = "Mozambique"
                        },
                        new
                        {
                            Id = new Guid("cb6e337e-5c13-40c5-8644-6d84fa80b8d4"),
                            Name = "Birmania"
                        },
                        new
                        {
                            Id = new Guid("c18eafd1-d718-42be-b4e7-f7957ce35af5"),
                            Name = "Namibia"
                        },
                        new
                        {
                            Id = new Guid("22782a4e-4eef-48dd-bdfc-11e211780b15"),
                            Name = "Nauru"
                        },
                        new
                        {
                            Id = new Guid("ec64c421-70ab-4f54-a85c-fb734856a39f"),
                            Name = "Nepal"
                        },
                        new
                        {
                            Id = new Guid("09290e82-04cf-4d73-ab40-1499b7a15407"),
                            Name = "Nicaragua"
                        },
                        new
                        {
                            Id = new Guid("f95e79e0-55b2-4e3a-8bbb-b25e3a8eba60"),
                            Name = "Níger"
                        },
                        new
                        {
                            Id = new Guid("f1fef602-ca1d-4048-8fd7-04c93099fe63"),
                            Name = "Nigeria"
                        },
                        new
                        {
                            Id = new Guid("50c19d6f-be89-4528-bd7b-5abd6b2faf24"),
                            Name = "Noruega"
                        },
                        new
                        {
                            Id = new Guid("9c2486fa-ef4f-4da7-8fff-419b28841d90"),
                            Name = "Nueva Zelanda"
                        },
                        new
                        {
                            Id = new Guid("400b3ca7-fe3b-4581-a721-fd2a6f92d682"),
                            Name = "Omán"
                        },
                        new
                        {
                            Id = new Guid("214275cf-aa30-4b1a-842a-7e76ad311c13"),
                            Name = "Países Bajos"
                        },
                        new
                        {
                            Id = new Guid("f8217bec-3e50-4c79-9751-10143ae9e735"),
                            Name = "Pakistán"
                        },
                        new
                        {
                            Id = new Guid("afdc812e-ead3-4c27-8f04-175e23779588"),
                            Name = "Palaos"
                        },
                        new
                        {
                            Id = new Guid("29df6755-8af5-4c9b-9292-104d122f607f"),
                            Name = "Panamá"
                        },
                        new
                        {
                            Id = new Guid("e15bf30c-2f53-4ab5-99e1-826ddd17c3c2"),
                            Name = "Papúa Nueva Guinea"
                        },
                        new
                        {
                            Id = new Guid("5ea06cb4-8baa-428c-8d5c-a2424f6d71b4"),
                            Name = "Paraguay"
                        },
                        new
                        {
                            Id = new Guid("ce779625-5836-4e40-9bd5-9657702fc3b0"),
                            Name = "Perú"
                        },
                        new
                        {
                            Id = new Guid("019065b4-e35c-47d9-99a9-1a1447989790"),
                            Name = "Polonia"
                        },
                        new
                        {
                            Id = new Guid("8a6e15bf-d0f9-439a-9298-5911229adace"),
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = new Guid("bcae80f2-bd15-497a-9b53-eb6601287dde"),
                            Name = "Qatar"
                        },
                        new
                        {
                            Id = new Guid("955d782b-874f-49e2-9954-8a732be088be"),
                            Name = "Reino Unido"
                        },
                        new
                        {
                            Id = new Guid("eb8671f3-0cef-4439-a971-e6cf258dc3cf"),
                            Name = "República Centroafricana"
                        },
                        new
                        {
                            Id = new Guid("5a35643b-311d-4646-b070-df2cfd51a808"),
                            Name = "República Dominicana"
                        },
                        new
                        {
                            Id = new Guid("717e7a36-e3b6-4b4e-8a67-7a638c777721"),
                            Name = "Rumanía / Rumania"
                        },
                        new
                        {
                            Id = new Guid("5546ab8c-f79f-4254-8403-589c905d529c"),
                            Name = "Rusia"
                        },
                        new
                        {
                            Id = new Guid("b6261339-7118-463f-bb3a-abd968004842"),
                            Name = "Ruanda"
                        },
                        new
                        {
                            Id = new Guid("a8f10f64-2112-4476-875b-f19ae7a9bf0a"),
                            Name = "San Cristóbal y Nieves"
                        },
                        new
                        {
                            Id = new Guid("dfba2d29-298c-4cc1-b912-9187834973ba"),
                            Name = "Islas Salomón"
                        },
                        new
                        {
                            Id = new Guid("5d4338f9-0f43-429c-9cff-2faa154155db"),
                            Name = "Samoa"
                        },
                        new
                        {
                            Id = new Guid("c5567525-3fe6-4a0c-a263-e19b560dace1"),
                            Name = "San Marino"
                        },
                        new
                        {
                            Id = new Guid("f5661aa0-3753-4758-9fd2-697536b2f55d"),
                            Name = "Santa Lucía"
                        },
                        new
                        {
                            Id = new Guid("6f4c511a-050e-4778-be89-10fd24e37291"),
                            Name = "Ciudad del Vaticano"
                        },
                        new
                        {
                            Id = new Guid("35ae1cdf-7fc4-4acf-aee9-f9d54b36b0b0"),
                            Name = "Santo Tomé y Príncipe"
                        },
                        new
                        {
                            Id = new Guid("61ca4a3c-76a9-4da1-ad9c-7f5d2278df09"),
                            Name = "San Vicente y las Granadinas"
                        },
                        new
                        {
                            Id = new Guid("42b83d90-43c6-4a67-8fbe-6fe2612b9cf7"),
                            Name = "Senegal"
                        },
                        new
                        {
                            Id = new Guid("003349c9-cc4e-4283-b96c-c85a40365d6a"),
                            Name = "Serbia"
                        },
                        new
                        {
                            Id = new Guid("920d7edf-5c19-4043-9d22-c91a487bfe22"),
                            Name = "Seychelles"
                        },
                        new
                        {
                            Id = new Guid("bfa45570-fc9c-4eb2-a9c7-f106f63ab227"),
                            Name = "Sierra Leona"
                        },
                        new
                        {
                            Id = new Guid("44d13672-9e8a-4467-b807-583115a72472"),
                            Name = "Singapur"
                        },
                        new
                        {
                            Id = new Guid("6106412d-11af-4361-a5db-f5d133319206"),
                            Name = "Siria"
                        },
                        new
                        {
                            Id = new Guid("ee3022de-9550-4d3b-9453-24efbd7eca3b"),
                            Name = "Somalia"
                        },
                        new
                        {
                            Id = new Guid("3ffd8620-3313-40e0-8f79-04572d9303f6"),
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            Id = new Guid("95e664f1-8cec-421c-b028-a3bf6720601c"),
                            Name = "Sudáfrica"
                        },
                        new
                        {
                            Id = new Guid("44759d98-a868-40e1-bb8a-25dea292e8f8"),
                            Name = "Sudán"
                        },
                        new
                        {
                            Id = new Guid("05cbc3c6-f439-428f-84d6-3798ddc6ec82"),
                            Name = "Sudán del Sur"
                        },
                        new
                        {
                            Id = new Guid("331c4e37-0e68-4b63-a956-f0426bb60000"),
                            Name = "Suecia"
                        },
                        new
                        {
                            Id = new Guid("4960827b-4cf7-4b8a-b0ea-11b0ba5ca61e"),
                            Name = "Suiza"
                        },
                        new
                        {
                            Id = new Guid("f1ce0b25-b8a0-4db4-a9a2-c520c48d4e35"),
                            Name = "Surinam"
                        },
                        new
                        {
                            Id = new Guid("8c052a0e-7eed-4002-809a-cf959ed409aa"),
                            Name = "Suazilandia"
                        },
                        new
                        {
                            Id = new Guid("06b0ae7f-75bb-4566-a9f8-d4fb1846a01f"),
                            Name = "Tailandia"
                        },
                        new
                        {
                            Id = new Guid("c2fd0274-7580-4734-bd6b-8125f749b16e"),
                            Name = "Tanzania"
                        },
                        new
                        {
                            Id = new Guid("6400f540-ffd4-4f6c-928c-34c8941e8d1b"),
                            Name = "Tayikistán"
                        },
                        new
                        {
                            Id = new Guid("dfa93433-8b25-499b-9a77-17f139027e8c"),
                            Name = "Timor Oriental"
                        },
                        new
                        {
                            Id = new Guid("c35b7cf9-bab3-4f1a-b18f-d4cb304eb3d5"),
                            Name = "Togo"
                        },
                        new
                        {
                            Id = new Guid("aaa731aa-de3c-4a79-aa29-76e2dd42b06a"),
                            Name = "Tonga"
                        },
                        new
                        {
                            Id = new Guid("5e8b4184-3dc3-498a-926e-441c2443233a"),
                            Name = "Trinidad y Tobago"
                        },
                        new
                        {
                            Id = new Guid("635c0515-877d-4107-bb74-35d727ba29f1"),
                            Name = "Túnez"
                        },
                        new
                        {
                            Id = new Guid("93e1173f-7435-4390-ba58-c22f6ed34f5f"),
                            Name = "Turkmenistán"
                        },
                        new
                        {
                            Id = new Guid("8d7bf27f-7d45-419a-9df7-1abe6d5ef4ef"),
                            Name = "Turquía"
                        },
                        new
                        {
                            Id = new Guid("6d300f86-0ea8-4985-bd85-24f07f5aca29"),
                            Name = "Tuvalu"
                        },
                        new
                        {
                            Id = new Guid("3a06246e-d66b-4878-b5bc-c80e7ecd07ad"),
                            Name = "Ucrania"
                        },
                        new
                        {
                            Id = new Guid("730a4b90-9d77-401e-bada-50bd3335699b"),
                            Name = "Uganda"
                        },
                        new
                        {
                            Id = new Guid("85482c08-c21d-4853-b3ef-f0a903cb6b33"),
                            Name = "Uruguay"
                        },
                        new
                        {
                            Id = new Guid("b918f473-0bce-48de-8421-1f8fbc5490ba"),
                            Name = "Uzbekistán"
                        },
                        new
                        {
                            Id = new Guid("9476ad2c-95a2-4bb4-875f-aad64431dee6"),
                            Name = "Vanuatu"
                        },
                        new
                        {
                            Id = new Guid("de9ff169-eb41-43e6-9e58-ad7d8c36258b"),
                            Name = "Venezuela"
                        },
                        new
                        {
                            Id = new Guid("e0ec2f5d-ccd8-48c2-93cb-e03b883359bb"),
                            Name = "Vietnam"
                        },
                        new
                        {
                            Id = new Guid("fac2afdb-333c-4333-b770-864e18445acb"),
                            Name = "Yemen"
                        },
                        new
                        {
                            Id = new Guid("38c0622c-6cbf-47bf-b9fb-67356febaa9b"),
                            Name = "Zambia"
                        },
                        new
                        {
                            Id = new Guid("91f3e528-8550-4bee-a1a3-0617d2b057ea"),
                            Name = "Zimbabue"
                        });
                });

            modelBuilder.Entity("Fenicia.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FiscalName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nif")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.Property<string>("TradeName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("Fenicia.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignamentDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DeliveryAddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Iva")
                        .HasColumnType("decimal(8,2)");

                    b.Property<int>("NumberItems")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("TerminationDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DeliveryAddressId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("Fenicia.Domain.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(8,2)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("Fenicia.Domain.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("varchar(9)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Dni")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("Fenicia.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Iva")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(8,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("Fenicia.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("Fenicia.Domain.Entities.Employee", b =>
                {
                    b.HasBaseType("Fenicia.Domain.Entities.Person");

                    b.Property<string>("Job")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(8,2)");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("Fenicia.Domain.Entities.Address", b =>
                {
                    b.HasOne("Fenicia.Domain.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fenicia.Domain.Entities.Customer", "Customer")
                        .WithMany("Addresses")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Fenicia.Domain.Entities.Person", "Person")
                        .WithMany("Addresses")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Country");

                    b.Navigation("Customer");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Fenicia.Domain.Entities.Order", b =>
                {
                    b.HasOne("Fenicia.Domain.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Fenicia.Domain.Entities.Address", "DeliveryAddress")
                        .WithMany("Orders")
                        .HasForeignKey("DeliveryAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fenicia.Domain.Entities.Employee", "Employee")
                        .WithMany("Orders")
                        .HasForeignKey("EmployeeId");

                    b.Navigation("Customer");

                    b.Navigation("DeliveryAddress");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Fenicia.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("Fenicia.Domain.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fenicia.Domain.Entities.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Fenicia.Domain.Entities.Person", b =>
                {
                    b.HasOne("Fenicia.Domain.Entities.User", "User")
                        .WithOne("Person")
                        .HasForeignKey("Fenicia.Domain.Entities.Person", "UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Fenicia.Domain.Entities.Product", b =>
                {
                    b.HasOne("Fenicia.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Fenicia.Domain.Entities.Employee", b =>
                {
                    b.HasOne("Fenicia.Domain.Entities.Person", null)
                        .WithOne()
                        .HasForeignKey("Fenicia.Domain.Entities.Employee", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fenicia.Domain.Entities.Address", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Fenicia.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Fenicia.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Fenicia.Domain.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Fenicia.Domain.Entities.Person", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("Fenicia.Domain.Entities.Product", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Fenicia.Domain.Entities.User", b =>
                {
                    b.Navigation("Person");
                });

            modelBuilder.Entity("Fenicia.Domain.Entities.Employee", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
