// <auto-generated />
using System;
using Fenicia.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Fenicia.Infrastructure.Migrations
{
    [DbContext(typeof(FeniciaDbContext))]
    partial class FeniciaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Fenicia.Domain.Entities.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ZipCode")
                        .HasMaxLength(25)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PersonId");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("Fenicia.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("Fenicia.Domain.Entities.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Country");

                    b.HasData(
                        new
                        {
                            Id = new Guid("97d4533b-c8a5-4450-9d43-864068bcf0c3"),
                            Name = "Afganistán"
                        },
                        new
                        {
                            Id = new Guid("2017f86d-ba97-440d-afdd-38e4ca466e81"),
                            Name = "Albania"
                        },
                        new
                        {
                            Id = new Guid("42a532d1-04d9-493e-ad76-146c9c5b2fa4"),
                            Name = "Alemania"
                        },
                        new
                        {
                            Id = new Guid("f4d21ae9-4fc6-465b-b40c-8a81fb5c910e"),
                            Name = "Andorra"
                        },
                        new
                        {
                            Id = new Guid("0f87e153-96ab-4e1b-9376-b60a939d3ad6"),
                            Name = "Angola"
                        },
                        new
                        {
                            Id = new Guid("0809f6df-8958-4aa4-bf11-e0bcb101834b"),
                            Name = "Antigua y Barbuda"
                        },
                        new
                        {
                            Id = new Guid("19233a95-244d-4a0b-b70f-a008eed2067c"),
                            Name = "Arabia Saudita"
                        },
                        new
                        {
                            Id = new Guid("8fa27636-b5b9-43ab-8153-25a8b2ef4a06"),
                            Name = "Argelia"
                        },
                        new
                        {
                            Id = new Guid("80e6bdec-0e19-4f64-9af5-b44041ccd21d"),
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = new Guid("4a09fec8-a165-4cbb-89da-2d11001a7ae7"),
                            Name = "Armenia"
                        },
                        new
                        {
                            Id = new Guid("d65a9393-5274-4889-be6a-f46af57f82b9"),
                            Name = "Australia"
                        },
                        new
                        {
                            Id = new Guid("c24bb2f2-7549-46c7-ba0e-be14aebc1f5c"),
                            Name = "Austria"
                        },
                        new
                        {
                            Id = new Guid("85446a3d-0185-4644-8262-c0bab4777943"),
                            Name = "Azerbaiyán"
                        },
                        new
                        {
                            Id = new Guid("c7b06cd3-d98c-4992-a24e-76a1f8ad9641"),
                            Name = "Bahamas"
                        },
                        new
                        {
                            Id = new Guid("357a1531-6e7a-4430-99ca-09a9ac4c4ed5"),
                            Name = "Bahréin"
                        },
                        new
                        {
                            Id = new Guid("a81192b7-8a31-41ce-af3b-848c64c06979"),
                            Name = "Bangladés"
                        },
                        new
                        {
                            Id = new Guid("eb4323c8-0e5c-4421-827e-bae8eeea2665"),
                            Name = "Barbados"
                        },
                        new
                        {
                            Id = new Guid("caf644a8-cae8-4b4a-9a14-142de33870d0"),
                            Name = "Bielorrusia"
                        },
                        new
                        {
                            Id = new Guid("2fa9498b-c1aa-403b-80ca-0418b90bb823"),
                            Name = "Bélgica"
                        },
                        new
                        {
                            Id = new Guid("ab3a3497-0a71-43fd-9f83-cd53b3d7f04c"),
                            Name = "Belice"
                        },
                        new
                        {
                            Id = new Guid("e6c401d9-38e0-4130-806e-dd29154279b2"),
                            Name = "Benín"
                        },
                        new
                        {
                            Id = new Guid("44cafb85-0620-4c95-b581-58980b70c871"),
                            Name = "Bután"
                        },
                        new
                        {
                            Id = new Guid("4bff07a0-05e9-46ca-b5f6-073857909c24"),
                            Name = "Bolivia"
                        },
                        new
                        {
                            Id = new Guid("71be8f7b-adf8-4e62-8cdd-1852808dbfed"),
                            Name = "Bosnia-Herzegovina"
                        },
                        new
                        {
                            Id = new Guid("e20e2db2-e92f-47dc-9a75-60e193d619b3"),
                            Name = "Botsuana"
                        },
                        new
                        {
                            Id = new Guid("f73291f3-c96e-4092-9c2a-f88fe9bcce4c"),
                            Name = "Brasil"
                        },
                        new
                        {
                            Id = new Guid("3767e496-953f-4b2b-916b-fa999d4aa9fc"),
                            Name = "Brunéi"
                        },
                        new
                        {
                            Id = new Guid("3c246c38-65ee-436e-af42-bb4dc0df7935"),
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Id = new Guid("4ecdd520-ab8e-42b7-bb0d-01622edac9b5"),
                            Name = "Burkina Faso"
                        },
                        new
                        {
                            Id = new Guid("3045c8ae-390b-4a3f-b70e-7aa6d94bac9c"),
                            Name = "Burundi"
                        },
                        new
                        {
                            Id = new Guid("41ce878f-aafa-4806-a9e6-d60447440c3e"),
                            Name = "Cabo Verde"
                        },
                        new
                        {
                            Id = new Guid("e52d3a38-a6e3-4498-8977-288a2bd8a7bd"),
                            Name = "Camboya"
                        },
                        new
                        {
                            Id = new Guid("74e0ef7c-57ca-4156-97fc-2e6ebec69fdb"),
                            Name = "Camerún"
                        },
                        new
                        {
                            Id = new Guid("9ce8753c-16bb-49ad-8117-77b762d7e5aa"),
                            Name = "Canadá"
                        },
                        new
                        {
                            Id = new Guid("41c60e88-cdba-46fd-ab38-53c786d59b97"),
                            Name = "Chad"
                        },
                        new
                        {
                            Id = new Guid("acb80233-5526-42f6-ad72-172bb5b59fee"),
                            Name = "República Checa"
                        },
                        new
                        {
                            Id = new Guid("318f8e62-d064-4923-bc62-af65fd8ce5e9"),
                            Name = "Chequia"
                        },
                        new
                        {
                            Id = new Guid("11c867ee-fa25-47ad-9cd1-0cc26656fa4e"),
                            Name = "Chile"
                        },
                        new
                        {
                            Id = new Guid("a8cafc00-a1dc-4a3c-8652-858d7f701b72"),
                            Name = "China"
                        },
                        new
                        {
                            Id = new Guid("f5717a33-924f-44d1-9632-c813d045d337"),
                            Name = "Chipre"
                        },
                        new
                        {
                            Id = new Guid("4ac8ed17-5f7b-4fcf-b32e-217e0f1b5f68"),
                            Name = "Colombia"
                        },
                        new
                        {
                            Id = new Guid("1f4af18e-55ce-4b24-9a33-43c94c4ead94"),
                            Name = "Comoras"
                        },
                        new
                        {
                            Id = new Guid("ff14e5c3-b602-4c67-b5fb-681cea3ca98f"),
                            Name = "Congo"
                        },
                        new
                        {
                            Id = new Guid("c06f3ce0-e7a0-40a6-b33c-3f9688623f5b"),
                            Name = "República Democrática del Congo"
                        },
                        new
                        {
                            Id = new Guid("872c9271-3a52-4f1a-8d28-fc048c5d96cb"),
                            Name = "Corea del Norte"
                        },
                        new
                        {
                            Id = new Guid("cd0c5966-49b0-4126-9332-df2d8e185fa7"),
                            Name = "Corea del Sur"
                        },
                        new
                        {
                            Id = new Guid("42db10cc-11f6-4bb3-b2a6-8e896a9513b7"),
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Id = new Guid("e9ef079b-8717-43ef-8fff-7826b2023eca"),
                            Name = "Costa de Marfil"
                        },
                        new
                        {
                            Id = new Guid("86cabb94-106d-43b3-b516-cf618a924787"),
                            Name = "Croacia"
                        },
                        new
                        {
                            Id = new Guid("4a49e947-a176-4a9f-b43a-e79e1ab78e22"),
                            Name = "Cuba"
                        },
                        new
                        {
                            Id = new Guid("e6af949d-e03e-4fe9-a1a7-5d799dc9e778"),
                            Name = "Dinamarca"
                        },
                        new
                        {
                            Id = new Guid("ffe867e6-ed82-4820-a87b-52ffa6de0b92"),
                            Name = "Yibuti"
                        },
                        new
                        {
                            Id = new Guid("193da4df-10d8-439e-99c7-0db566519323"),
                            Name = "Dominica"
                        },
                        new
                        {
                            Id = new Guid("b51247ab-4376-4c53-87de-29b01667effa"),
                            Name = "Ecuador"
                        },
                        new
                        {
                            Id = new Guid("21746609-9a31-4750-9747-d00dcf8b8562"),
                            Name = "Egipto"
                        },
                        new
                        {
                            Id = new Guid("70ce0bc9-803a-4fe9-b3a9-686a13c0864c"),
                            Name = "El Salvador"
                        },
                        new
                        {
                            Id = new Guid("a34b712c-e0af-435f-b602-12408c529159"),
                            Name = "Emiratos Árabes Unidos"
                        },
                        new
                        {
                            Id = new Guid("b2fe24cc-c15c-4d30-bc8a-cae3a6f72f58"),
                            Name = "Eritrea"
                        },
                        new
                        {
                            Id = new Guid("33a945ac-a227-4b81-a88e-67b3707b5619"),
                            Name = "Eslovaquia"
                        },
                        new
                        {
                            Id = new Guid("4a46ec15-8948-4cef-8e6c-9d13708e4d29"),
                            Name = "Eslovenia"
                        },
                        new
                        {
                            Id = new Guid("d30c1810-98b3-47c5-9f54-a0ef87d49858"),
                            Name = "España"
                        },
                        new
                        {
                            Id = new Guid("66607da3-f666-4304-8479-65d9c18db62e"),
                            Name = "Estados Unidos"
                        },
                        new
                        {
                            Id = new Guid("b234b3c8-889b-4b26-9324-a6fe5903d677"),
                            Name = "Estonia"
                        },
                        new
                        {
                            Id = new Guid("91ca5ebf-3ee5-4943-be46-887e12d326c1"),
                            Name = "Etiopía"
                        },
                        new
                        {
                            Id = new Guid("174957cb-e7c2-4fa7-aa5c-2744f293f159"),
                            Name = "Fiyi"
                        },
                        new
                        {
                            Id = new Guid("608d4c39-350d-4394-be0d-df33c4df7bc5"),
                            Name = "Filipinas"
                        },
                        new
                        {
                            Id = new Guid("d766b754-6714-4f33-afc4-26ed81aa95af"),
                            Name = "Finlandia"
                        },
                        new
                        {
                            Id = new Guid("2daac162-09f2-4bfe-8b7c-816cf22d2ebd"),
                            Name = "Francia"
                        },
                        new
                        {
                            Id = new Guid("97f9997e-ee19-4fbf-a256-5037c4f3ded8"),
                            Name = "Gabón"
                        },
                        new
                        {
                            Id = new Guid("ba7268f4-5eda-4811-b619-6b0acbdb4750"),
                            Name = "Gambia"
                        },
                        new
                        {
                            Id = new Guid("b7f110b0-1612-4e4c-893c-5833a817109c"),
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = new Guid("4ca13528-6c5f-484f-985b-006dd8ba1ed9"),
                            Name = "Ghana"
                        },
                        new
                        {
                            Id = new Guid("87c0bc65-a158-4357-aa8b-732b20f80a00"),
                            Name = "Granada"
                        },
                        new
                        {
                            Id = new Guid("9d619bb3-7582-497f-92d2-7a66e21b0919"),
                            Name = "Grecia"
                        },
                        new
                        {
                            Id = new Guid("65a621b4-b59d-4ffe-a599-040ff99132e1"),
                            Name = "Guatemala"
                        },
                        new
                        {
                            Id = new Guid("2c184ad2-a154-4a9f-b5c5-23298ecd1007"),
                            Name = "Guinea"
                        },
                        new
                        {
                            Id = new Guid("e6b359aa-a0ac-4860-9df9-d3c9f8722a4d"),
                            Name = "Guinea-Bissau"
                        },
                        new
                        {
                            Id = new Guid("dcf5f633-ff72-448b-b888-7123d4d9734f"),
                            Name = "Guinea Ecuatorial"
                        },
                        new
                        {
                            Id = new Guid("2e1e9917-3ff4-4133-b615-eb32765ae7ad"),
                            Name = "Guyana"
                        },
                        new
                        {
                            Id = new Guid("a66528f3-a310-459a-9560-e7dfff5cc67b"),
                            Name = "Haití"
                        },
                        new
                        {
                            Id = new Guid("1483194b-8aff-4586-afcd-35e3ecdef3fe"),
                            Name = "Honduras"
                        },
                        new
                        {
                            Id = new Guid("e922382f-d93b-4565-bff5-8cca2bbe9d1f"),
                            Name = "Hungría"
                        },
                        new
                        {
                            Id = new Guid("5f9ca932-5ffe-4568-9ba0-aea38e43e879"),
                            Name = "India"
                        },
                        new
                        {
                            Id = new Guid("3187c21f-495d-476a-8ebf-06535f7d662a"),
                            Name = "Indonesia"
                        },
                        new
                        {
                            Id = new Guid("2184f64e-0dae-4e89-9fd7-2f77b558a48a"),
                            Name = "Irán"
                        },
                        new
                        {
                            Id = new Guid("9b317850-eab2-4ef1-9727-f44285084533"),
                            Name = "Iraq"
                        },
                        new
                        {
                            Id = new Guid("7b1ea92a-f218-4a29-8d98-390aa7afe0bc"),
                            Name = "Irlanda"
                        },
                        new
                        {
                            Id = new Guid("04953d2e-fe5e-4788-82a5-33dec8856160"),
                            Name = "Islandia"
                        },
                        new
                        {
                            Id = new Guid("e2e618da-657a-4127-875d-f8f2fbb9d70f"),
                            Name = "Israel"
                        },
                        new
                        {
                            Id = new Guid("45091f1c-e509-466d-8922-43b428cfcc77"),
                            Name = "Italia"
                        },
                        new
                        {
                            Id = new Guid("0b898297-d275-4682-83b6-19c46352f318"),
                            Name = "Jamaica"
                        },
                        new
                        {
                            Id = new Guid("dae95d22-8437-4594-9073-560dc2a5367b"),
                            Name = "Japón"
                        },
                        new
                        {
                            Id = new Guid("aa2b39bc-aa51-4e45-8956-80826969b8b0"),
                            Name = "Jordania"
                        },
                        new
                        {
                            Id = new Guid("fe1d9507-60d1-47aa-9030-128079cf2817"),
                            Name = "Kazajistán"
                        },
                        new
                        {
                            Id = new Guid("43e7e98c-6f2d-4ec3-9343-96ded8c47d6f"),
                            Name = "Kenia"
                        },
                        new
                        {
                            Id = new Guid("89c4002e-67f4-4094-9b96-e99732f1f4cc"),
                            Name = "Kirguistán"
                        },
                        new
                        {
                            Id = new Guid("357d33f5-9f14-4fc7-877e-8865bab3ca15"),
                            Name = "Kiribati"
                        },
                        new
                        {
                            Id = new Guid("1a132eb7-2a0b-470b-8687-18e6ea8fc0f0"),
                            Name = "Kuwait"
                        },
                        new
                        {
                            Id = new Guid("47b90428-901f-4faf-a7e0-dcbff2557304"),
                            Name = "Laos"
                        },
                        new
                        {
                            Id = new Guid("12a22c99-2f8e-4b9f-a6b2-d3403dac1278"),
                            Name = "Lesoto"
                        },
                        new
                        {
                            Id = new Guid("f6054a30-73b5-4d7a-a458-2b57d0c3c3ef"),
                            Name = "Letonia"
                        },
                        new
                        {
                            Id = new Guid("a76c9b98-e380-45b6-8456-bf855f1fd6d2"),
                            Name = "Líbano"
                        },
                        new
                        {
                            Id = new Guid("ba8ccf04-f5d7-44b7-801c-cfa4f6095194"),
                            Name = "Liberia"
                        },
                        new
                        {
                            Id = new Guid("afbfb669-c77b-462e-b55c-a557cf5c4ffc"),
                            Name = "Libia"
                        },
                        new
                        {
                            Id = new Guid("ac04779a-f616-4688-9c59-f313400bf142"),
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            Id = new Guid("a34c44ab-7ca2-4a50-bb46-73fcf08febb2"),
                            Name = "Lituania"
                        },
                        new
                        {
                            Id = new Guid("f609691e-7546-46dc-a572-4a4bdc85046c"),
                            Name = "Luxemburgo"
                        },
                        new
                        {
                            Id = new Guid("5ff608b7-2602-4cf3-81c9-188e5ed29588"),
                            Name = "Macedonia"
                        },
                        new
                        {
                            Id = new Guid("c2351853-d5f6-45ba-a4a2-24f50f3807b4"),
                            Name = "Madagascar"
                        },
                        new
                        {
                            Id = new Guid("52099703-ee97-4134-be37-c0a30f3b6aed"),
                            Name = "Malasia"
                        },
                        new
                        {
                            Id = new Guid("05b07132-2f81-47c5-9974-ab7ca659829d"),
                            Name = "Malaui"
                        },
                        new
                        {
                            Id = new Guid("6f47d2d1-f5b7-4354-b237-2d6016906c9f"),
                            Name = "Maldivas"
                        },
                        new
                        {
                            Id = new Guid("89cac102-aa54-405c-b51b-a7271fc722b1"),
                            Name = "Mali / Malí"
                        },
                        new
                        {
                            Id = new Guid("006bff81-8775-476d-962e-baea4e6ab4cf"),
                            Name = "Malta"
                        },
                        new
                        {
                            Id = new Guid("301fb53c-87e4-460b-92fa-39a2b0bc1bf4"),
                            Name = "Marruecos"
                        },
                        new
                        {
                            Id = new Guid("ed3a93c9-39a3-4d56-9885-542ea6d0a2ae"),
                            Name = "Islas Marshall"
                        },
                        new
                        {
                            Id = new Guid("58e0ac6d-f190-460b-8ac0-14e6889fae54"),
                            Name = "Mauricio"
                        },
                        new
                        {
                            Id = new Guid("67681bbe-9131-4746-9c41-53b58ae37de1"),
                            Name = "Mauritania"
                        },
                        new
                        {
                            Id = new Guid("c4c1c3cf-0c2a-45b2-b425-9acb2916432f"),
                            Name = "México"
                        },
                        new
                        {
                            Id = new Guid("4278bd1b-329c-42d3-ae36-91d3cc28224a"),
                            Name = "Micronesia"
                        },
                        new
                        {
                            Id = new Guid("df876e7e-12d2-4b04-88f0-794eb96991b6"),
                            Name = "Moldavia"
                        },
                        new
                        {
                            Id = new Guid("b6354aff-b1b8-4d14-8f32-3a8307e78128"),
                            Name = "Mónaco"
                        },
                        new
                        {
                            Id = new Guid("7b4574c9-f59e-4e82-92b1-e92c9f20ac44"),
                            Name = "Mongolia"
                        },
                        new
                        {
                            Id = new Guid("3fcab056-77b5-49fe-9164-9552563750db"),
                            Name = "Montenegro"
                        },
                        new
                        {
                            Id = new Guid("8765ea0c-232a-4e4c-ba9c-4a42c9525c51"),
                            Name = "Mozambique"
                        },
                        new
                        {
                            Id = new Guid("826f8c36-6cb5-4bfd-9272-d9660b9a13c7"),
                            Name = "Birmania"
                        },
                        new
                        {
                            Id = new Guid("3bf51dfa-cf8d-416e-93d8-561e62b16047"),
                            Name = "Namibia"
                        },
                        new
                        {
                            Id = new Guid("50a7b36a-08d2-4fc1-a778-da540bedeaf0"),
                            Name = "Nauru"
                        },
                        new
                        {
                            Id = new Guid("b489a0fc-d8ac-4cd8-b7e6-63637bd63eb2"),
                            Name = "Nepal"
                        },
                        new
                        {
                            Id = new Guid("3fdf425b-2d92-45b2-80ff-fccfee3b2130"),
                            Name = "Nicaragua"
                        },
                        new
                        {
                            Id = new Guid("ac59ca43-cc99-447d-9492-ca33886d7623"),
                            Name = "Níger"
                        },
                        new
                        {
                            Id = new Guid("592e3870-937d-465f-a894-bc3696a16ff5"),
                            Name = "Nigeria"
                        },
                        new
                        {
                            Id = new Guid("df164680-0cec-49bb-a1da-1e65f2e5ac00"),
                            Name = "Noruega"
                        },
                        new
                        {
                            Id = new Guid("3734e849-ec53-45f5-b470-740c7aa4702f"),
                            Name = "Nueva Zelanda"
                        },
                        new
                        {
                            Id = new Guid("ff51e9d0-8894-4801-a4a6-5ece470fe76d"),
                            Name = "Omán"
                        },
                        new
                        {
                            Id = new Guid("8e789420-c1b6-4dcf-8f22-ee1f8d80c0e4"),
                            Name = "Países Bajos"
                        },
                        new
                        {
                            Id = new Guid("090d1d5b-2b55-4305-8dad-4f46e3792c5d"),
                            Name = "Pakistán"
                        },
                        new
                        {
                            Id = new Guid("9dfda21f-0501-451d-8850-6ba0ff95306b"),
                            Name = "Palaos"
                        },
                        new
                        {
                            Id = new Guid("cab80088-facd-4ca9-b57f-8c25c2816937"),
                            Name = "Panamá"
                        },
                        new
                        {
                            Id = new Guid("58ad3f5d-1d2e-4ffa-81bd-9f2f73a80de7"),
                            Name = "Papúa Nueva Guinea"
                        },
                        new
                        {
                            Id = new Guid("8b2be02d-4d35-4df9-a301-c4ac6f9f5d8b"),
                            Name = "Paraguay"
                        },
                        new
                        {
                            Id = new Guid("d52cd213-77a3-48bf-90ae-1a62a1901531"),
                            Name = "Perú"
                        },
                        new
                        {
                            Id = new Guid("0ae64ba3-8b6a-4d3f-afef-757616eea70e"),
                            Name = "Polonia"
                        },
                        new
                        {
                            Id = new Guid("e256160e-dbef-4288-bd34-aec0ac056d44"),
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = new Guid("9764cc0e-6b5e-4e47-b1d3-ff0a5e6aa771"),
                            Name = "Qatar"
                        },
                        new
                        {
                            Id = new Guid("af19b47a-e054-49e1-97b5-b1102b6a99e5"),
                            Name = "Reino Unido"
                        },
                        new
                        {
                            Id = new Guid("ca90aa27-7f46-4140-bcd2-479a44af6f5c"),
                            Name = "República Centroafricana"
                        },
                        new
                        {
                            Id = new Guid("e5cb6341-9684-4a8f-b523-331c2ea28908"),
                            Name = "República Dominicana"
                        },
                        new
                        {
                            Id = new Guid("9d9b4812-c668-4c49-929d-87eb367c73a7"),
                            Name = "Rumanía / Rumania"
                        },
                        new
                        {
                            Id = new Guid("1f0142f9-71df-483d-bcea-f6045bc78960"),
                            Name = "Rusia"
                        },
                        new
                        {
                            Id = new Guid("cc33c331-b229-49e8-9eca-54464dd89c07"),
                            Name = "Ruanda"
                        },
                        new
                        {
                            Id = new Guid("cf32388a-ecdb-4345-9ee3-5698e923a766"),
                            Name = "San Cristóbal y Nieves"
                        },
                        new
                        {
                            Id = new Guid("fe92c0d1-6fcc-476a-9642-20cab3d13412"),
                            Name = "Islas Salomón"
                        },
                        new
                        {
                            Id = new Guid("af13eda4-2d41-4641-ba1b-97ad4738ed43"),
                            Name = "Samoa"
                        },
                        new
                        {
                            Id = new Guid("5a74468e-6593-46a0-89ca-073e7c662948"),
                            Name = "San Marino"
                        },
                        new
                        {
                            Id = new Guid("95bc010f-d24d-4f34-aa76-24e9213322c4"),
                            Name = "Santa Lucía"
                        },
                        new
                        {
                            Id = new Guid("0e41dedb-3496-4b9c-8950-e3089cfa0916"),
                            Name = "Ciudad del Vaticano"
                        },
                        new
                        {
                            Id = new Guid("58e23c9f-0b83-4984-8a12-353274a2a2f0"),
                            Name = "Santo Tomé y Príncipe"
                        },
                        new
                        {
                            Id = new Guid("6e3685b7-a732-4687-a96e-1e54bf934314"),
                            Name = "San Vicente y las Granadinas"
                        },
                        new
                        {
                            Id = new Guid("72a638cc-f314-4872-a4e4-fa6eda0d70f1"),
                            Name = "Senegal"
                        },
                        new
                        {
                            Id = new Guid("455a6673-3305-4bb7-be6b-e8b68ed75ada"),
                            Name = "Serbia"
                        },
                        new
                        {
                            Id = new Guid("ccae4c25-a8ee-44de-9a47-27e79402916e"),
                            Name = "Seychelles"
                        },
                        new
                        {
                            Id = new Guid("d34a1a87-0bc0-4998-ae18-515e4b615428"),
                            Name = "Sierra Leona"
                        },
                        new
                        {
                            Id = new Guid("34eb7482-d0c2-407c-a6ab-2d5f4eff6b21"),
                            Name = "Singapur"
                        },
                        new
                        {
                            Id = new Guid("4601d095-08d9-4f7f-8102-48f4d3731866"),
                            Name = "Siria"
                        },
                        new
                        {
                            Id = new Guid("2785d839-09bf-474e-a7bc-61a8067916a4"),
                            Name = "Somalia"
                        },
                        new
                        {
                            Id = new Guid("c7352e50-1471-4aba-95de-78b464baf072"),
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            Id = new Guid("c2d1d74b-5e4b-44f6-8b59-a4cb668f1305"),
                            Name = "Sudáfrica"
                        },
                        new
                        {
                            Id = new Guid("33308e75-ca1d-42c8-8fc9-84df823ef395"),
                            Name = "Sudán"
                        },
                        new
                        {
                            Id = new Guid("7bfcf654-c7cc-4863-b41a-d6d5f2190aef"),
                            Name = "Sudán del Sur"
                        },
                        new
                        {
                            Id = new Guid("10601a68-92a8-4d2c-9043-3fb09af3ad87"),
                            Name = "Suecia"
                        },
                        new
                        {
                            Id = new Guid("a0d4c33e-6831-4f16-bd06-21e78a388405"),
                            Name = "Suiza"
                        },
                        new
                        {
                            Id = new Guid("70b961f8-a111-43f1-ba7d-2b58ce07b574"),
                            Name = "Surinam"
                        },
                        new
                        {
                            Id = new Guid("745b6555-d0bc-48c8-a10a-7afb26ba6e88"),
                            Name = "Suazilandia"
                        },
                        new
                        {
                            Id = new Guid("0a8a9953-4fdb-4acc-97b6-861759bdc592"),
                            Name = "Tailandia"
                        },
                        new
                        {
                            Id = new Guid("ef45eb28-0d42-4477-8f5a-fcd7e50a1ca2"),
                            Name = "Tanzania"
                        },
                        new
                        {
                            Id = new Guid("61092099-9ca0-4b88-8c66-dbc7ea8af47f"),
                            Name = "Tayikistán"
                        },
                        new
                        {
                            Id = new Guid("179a8783-e02a-40f6-b72c-43596f220be4"),
                            Name = "Timor Oriental"
                        },
                        new
                        {
                            Id = new Guid("34a7a506-842b-4ae1-a6c5-b3966b78a77b"),
                            Name = "Togo"
                        },
                        new
                        {
                            Id = new Guid("a55b2abd-d175-46f2-b468-f67996f9d530"),
                            Name = "Tonga"
                        },
                        new
                        {
                            Id = new Guid("485072e0-e536-478b-8e8b-0dc5baa1b6c8"),
                            Name = "Trinidad y Tobago"
                        },
                        new
                        {
                            Id = new Guid("59824205-537a-440b-9f9c-f1c34e1afdac"),
                            Name = "Túnez"
                        },
                        new
                        {
                            Id = new Guid("69c143e0-0c86-4086-8707-e6e0a5e5cacf"),
                            Name = "Turkmenistán"
                        },
                        new
                        {
                            Id = new Guid("ad5595bd-6142-479e-b892-be40bbd4d1b0"),
                            Name = "Turquía"
                        },
                        new
                        {
                            Id = new Guid("f737ff09-4596-4544-ad34-296f5fa36777"),
                            Name = "Tuvalu"
                        },
                        new
                        {
                            Id = new Guid("9d6ed9fb-68de-4d13-970b-7bc179308321"),
                            Name = "Ucrania"
                        },
                        new
                        {
                            Id = new Guid("0b130dba-d30d-4220-8fc1-20abebc2349a"),
                            Name = "Uganda"
                        },
                        new
                        {
                            Id = new Guid("479daf8a-0aa4-4d14-8ff5-bbe7936895a6"),
                            Name = "Uruguay"
                        },
                        new
                        {
                            Id = new Guid("11622fca-0608-4f5a-a44c-d76a970b9d36"),
                            Name = "Uzbekistán"
                        },
                        new
                        {
                            Id = new Guid("22523c5b-2cb6-49c5-9db0-bdfe91f8328d"),
                            Name = "Vanuatu"
                        },
                        new
                        {
                            Id = new Guid("7151cf98-2d9e-4d75-bf5d-dec518d4daad"),
                            Name = "Venezuela"
                        },
                        new
                        {
                            Id = new Guid("13d4e022-19a3-410c-9cf3-a9b0852898fe"),
                            Name = "Vietnam"
                        },
                        new
                        {
                            Id = new Guid("b3a87936-f146-410f-9c4e-c251c3a33ec0"),
                            Name = "Yemen"
                        },
                        new
                        {
                            Id = new Guid("2ac04d4a-31b9-4bd8-8536-abb4aac822db"),
                            Name = "Zambia"
                        },
                        new
                        {
                            Id = new Guid("137cd154-27b2-48f0-8f9a-77d8d622388b"),
                            Name = "Zimbabue"
                        });
                });

            modelBuilder.Entity("Fenicia.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FiscalName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nif")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.Property<string>("TradeName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("Fenicia.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignamentDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DeliveryAddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Iva")
                        .HasColumnType("decimal(8,2)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("TerminationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DeliveryAddressId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("Fenicia.Domain.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(8,2)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("Fenicia.Domain.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("varchar(9)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Dni")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("Fenicia.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(8,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("Fenicia.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("Fenicia.Domain.Entities.Employee", b =>
                {
                    b.HasBaseType("Fenicia.Domain.Entities.Person");

                    b.Property<string>("Job")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(8,2)");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("Fenicia.Domain.Entities.Address", b =>
                {
                    b.HasOne("Fenicia.Domain.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fenicia.Domain.Entities.Customer", "Customer")
                        .WithMany("Addresses")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Fenicia.Domain.Entities.Person", "Person")
                        .WithMany("Addresses")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Country");

                    b.Navigation("Customer");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Fenicia.Domain.Entities.Order", b =>
                {
                    b.HasOne("Fenicia.Domain.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Fenicia.Domain.Entities.Address", "DeliveryAddress")
                        .WithMany("Orders")
                        .HasForeignKey("DeliveryAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fenicia.Domain.Entities.Employee", "Employee")
                        .WithMany("Orders")
                        .HasForeignKey("EmployeeId");

                    b.Navigation("Customer");

                    b.Navigation("DeliveryAddress");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Fenicia.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("Fenicia.Domain.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fenicia.Domain.Entities.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Fenicia.Domain.Entities.Person", b =>
                {
                    b.HasOne("Fenicia.Domain.Entities.User", "User")
                        .WithOne("Person")
                        .HasForeignKey("Fenicia.Domain.Entities.Person", "UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Fenicia.Domain.Entities.Product", b =>
                {
                    b.HasOne("Fenicia.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Fenicia.Domain.Entities.Employee", b =>
                {
                    b.HasOne("Fenicia.Domain.Entities.Person", null)
                        .WithOne()
                        .HasForeignKey("Fenicia.Domain.Entities.Employee", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fenicia.Domain.Entities.Address", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Fenicia.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Fenicia.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Fenicia.Domain.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Fenicia.Domain.Entities.Person", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("Fenicia.Domain.Entities.Product", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Fenicia.Domain.Entities.User", b =>
                {
                    b.Navigation("Person");
                });

            modelBuilder.Entity("Fenicia.Domain.Entities.Employee", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
